# See https://reuse.software/spec-3.3/#reusetoml for specification
version = 1

[[annotations]]
path = ["**"]
SPDX-FileCopyrightText = "2024 Deutsche Telekom AG"
SPDX-License-Identifier = "Apache-2.0"
