name: Continuous Integration (CI)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - './LICENSES'
      
  pull_request:
    branches: [ main ]
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - './LICENSES'


jobs:
  
    ktlint:
      runs-on: ubuntu-24.04
      steps:
        - name: "Checkout repository"
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
        - name: "Set up JDK 17"
          uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
          with:
            distribution: "temurin"
            java-version: 17
        
        - name: "Setup Gradle"
          uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
        
        - name: "Run Kotlin linter ktlint"
          run: ./gradlew ktlintCheck

        - name: "Upload ktlint reports"
          uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
          with:
            name: ktlint-reports
            path: /workspaces/CityKey-Android/app/build/reports/ktlint/
            retention-days: 5
            compression-level: 9

    unit-tests:
        runs-on: ubuntu-24.04
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            
            - name: "Set up JDK 17"
              uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
              with:
                distribution: "temurin"
                java-version: 17
            
            - name: "Setup Gradle"
              uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
           
            - name: "Run unit tests with coverage"
              run: ./gradlew test
            
            - name: "Upload coverage to codecov"
              uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                flags: unit-tests
                fail_ci_if_error: true
            
            - name: "Upload jacoco artifacts"
              uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
              with:
                name: test-results
                path: app/build/reports/tests/


    build-debug:
      runs-on: ubuntu-24.04
      needs: unit-tests
      permissions:
        contents: write

      steps:
          - name: "Checkout repository"
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            
          - name: "Set up JDK 17"
            uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
            with:
              distribution: "temurin"
              java-version: 17
            
          - name: "Setup Gradle"
            uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
            with:
              build-scan-publish: true
              build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
              build-scan-terms-of-use-agree: "yes"
      
          - name: "Build Debug APK"
            run: |
              ./gradlew assembleDebug
      
          - name: "Archive Debug APK Build"
            uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
            with:
              path: ./**/*.apk
